version: "3.8"
services:
  redis:
    image: redis:4.0
    container_name: redis-ms-room-services
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 10s
      retries: 10
  app:
    build: .
    image: ms-room-services
    restart: always
    ports:
      - 8000:8000
    networks:
      - backend
    links:
      - redis
    environment:
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      REDIS_HOST: redis-ms-room-services
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
      - ./:/app
      - /app/vendor
    depends_on:
      redis:
        condition: service_healthy
networks:
  backend:
    driver: bridge
